Refactor luks role stdout for reuse

diff --git a/roles/luks/templates/mount-encrypted-drives.j2 b/roles/luks/templates/mount-encrypted-drives.j2
--- a/roles/luks/templates/mount-encrypted-drives.j2
+++ b/roles/luks/templates/mount-encrypted-drives.j2
@@ -43,34 +43,39 @@ echo -e $nc
 echo "Now, these LUKS mappings will be unlocked and mapped to /dev/mapper/"
 {% for item in luks_mappings | unique('attribute', 'luks_id') %}
 {% if item.luks_id is not none %}
-echo -e "${bl}blkid: {{ item.luks_id | truncate(13) }}... => /dev/mapper/{{ item.luks_map }}"
+echo -e "${bl}{{ item.luks_id }} => /dev/mapper/{{ item.luks_map }}"
 {% endif %}
 {% endfor %}
 echo -e "$nc"
 
+_LUKS_SUCCESS="${gr}Successfully unlocked LUKS container!${nc}"
+_LUKS_FAIL="${rd}There was a problem unlocking this container!${nc}"
+_LUKS_SUGGEST="${yl}Is the device already mounted?\
+Is the volume UUID valid? Is the passphrase correct?${nc}"
 {% for item in luks_mappings | unique('attribute', 'luks_id') %}
 echo "Unlocking container mapped to LUKS map {{ item.luks_map }}"
 echo $luksKey | sudo cryptsetup open /dev/disk/by-uuid/{{ item.luks_id }} {{ item.luks_map }} \
-    && echo -e "${gr}Successfully unlocked LUKS container map {{ item.luks_map }}${nc}" \
-    || echo -e "${rd}There was a problem unlocking {{ item.luks_map }}${yl}\nIs the device already mounted? Is it a valid volume UUID?${nc}"
+    && echo -e ${_LUKS_SUCCESS} || echo -e "${_LUKS_FAIL}\n${_LUKS_SUGGEST}"
 echo -e $nc
 
 {% endfor %}
 echo
 
-# # Mount the volumes to their mount paths and options
-# #===================================================
-# _MOUNT_SUCCESS="${gr}Succesfully mounted volume$!{nc}"
-# _MOUNT_FAIL="${rd}ERROR: Something went wrong mounting this drive!\n${bl}Skipping...${nc}"
-# echo "These mount points will be mounted by their respective volumes:"
-# {% for item in luks_mappings | unique('attribute', 'mount') %}
-# echo -e "${bl}{{ item.luks_map }} => {{ item.mount }}${nc}"
-# {% endfor %}
-# echo
+# Mount the volumes to their mount paths and options
+#===================================================
+echo "These mount points will be mounted by their respective volumes:"
+{% for item in luks_mappings | unique('attribute', 'mount') %}
+echo -e "${bl}{{ item.luks_map }} => {{ item.mount }} ({{ mount_opts | default('defaults') }})${nc}"
+{% endfor %}
+echo
 
-# {% for item in luks_mappings | unique('attribute', 'mount') %}
-# echo -e "Mounting ${bl}{{ item.mount }}${nc} with opts ${bl}{{ item.mount_opts }}${nc}..."
-# sudo mount {{ item.luks_map }} {{ item.mount }} -o {{ item.mount_opts }} \
-#     && echo -e $_MOUNT_SUCCESS || echo -e $_MOUNT_FAIL
-# {% endfor %}
-# echo
+_MOUNT_SUCCESS="${gr}Succesfully mounted volume$!{nc}"
+_MOUNT_FAIL="${rd}ERROR: Something went wrong mounting this drive!\n${bl}Skipping...${nc}"
+{% for item in luks_mappings | unique('attribute', 'mount') %}
+echo -e "Mounting ${bl}{{ item.mount }}${nc} with opts ${bl}{{ item.mount_opts | default('defaults') }}${nc}"
+sudo mount /dev/mapper/{{ item.luks_map }} {{ item.mount }} \
+    -o {{ item.mount_opts | default('defaults') }} && echo -e $_MOUNT_SUCCESS || echo -e $_MOUNT_FAIL
+echo
+
+{% endfor %}
+echo
